[workspace]
resolver = "3"
members = ["cspcl", "cspcl-sys", "hardy-cspcl"]
[workspace.package]
edition = "2024"

[patch."https://github.com/ricktaylor/hardy.git"]
hardy-async = { git = "https://github.com/hugoponthieu/hardy.git", branch = "cspcl-patches" }
hardy-bpa = { git = "https://github.com/hugoponthieu/hardy.git", branch = "cspcl-patches" }
hardy-bpv7 = { git = "https://github.com/hugoponthieu/hardy.git", branch = "cspcl-patches" }
