[package]
name = "cspcl"
version = "0.4.0"
edition = "2024"
description = "Rust bindings for the cspcl library"
authors = ["cspcl contributors"]
license = "MIT"
repository = "https://github.com/d3tn/cspcl"
readme = "README.md"
keywords = ["cspcl"]

[dependencies]
cspcl-sys = { version = "0.3", path = "../cspcl-sys" }
futures = { version = "0.3", features = ["alloc"] }
tokio = { version = "1.52.3", features = ["rt"] }
