[package]
name = "hardy-cspcl"
version = "0.1.0"
edition.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = []
serde = ["dep:serde", "hardy-bpv7/serde"]
instrument = ["tracing/attributes"]

[dependencies]
hardy-bpa = { git = "https://github.com/ricktaylor/hardy.git" }
hardy-async = { git = "https://github.com/ricktaylor/hardy.git" }
hardy-bpv7 = { git = "https://github.com/ricktaylor/hardy.git" }
tracing = { version = "0.1.44", default-features = false }
thiserror = "2.0.18"
tokio = { version = "1.51.1", features = ["time"] }
serde = { version = "1.0.228", features = ["derive"], optional = true }
cspcl-bindings = { path = "../cspcl", package = "cspcl" }
futures-util = "0.3.32"
