[package]
name = "cspcl-sys"
version = "0.3.0"
edition = "2024"
description = "Raw FFI bindings for the cspcl library"
authors = ["cspcl contributors"]
license = "MIT"
repository = "https://github.com/d3tn/cspcl"
build = "build.rs"
links = "cspcl"
include = [
  "build.rs",
  "src/**/*",
  "c_src/cspcl.h",
  "c_src/cspcl.c",
  "c_src/cspcl_config.h",
]

[dependencies]

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2"
